name: LoginTP
version: '1.0'
main: org.network.dg32z.logintp.Main
api-version: '1.20'
author: Dg32z_
commands:
  lt:
    description: "Main command of LoginTeleport"
    usage: /lt <1>
    permission: "lt.cmd"
    permission-message: "您没有权限运行该指令"
